server:
  port: 9090
  servlet:
    context-path: /api
    session:
      timeout: 30m


spring:
  main:
    allow-circular-references: true
  mvc:
    throw-exception-if-no-handler-found: true
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3307/performance?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd hh:mm:ss
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

camunda:
  bpm:
    database:
      type: mysql
      schema-update: true
    webapp:
      index-redirect-enabled: true
    admin-user:
      id: admin
      password: admin123
    auto-deployment-enabled: false

mybatis-plus:
  global-config:
    db-config:
      table-prefix: #tb_
  configuration:
    #驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml

