version: '3.8'
services:
  performance_api-mysql:
    container_name: performance_api-mysql
    image: mysql:8.0.23
    build:
      context: ./mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - /mnt/docker/mysql/performance_api:/var/lib/mysql
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'root'
      MYSQL_ROOT_PASSWORD: root

